# values.yaml

deployment:
  name: myapachepod-deployment
  replicas: 2  # You can specify the desired number of replicas here

appLabel: apache  # This should match the label used in your Deployment and Service

image:
  tag: latest  # Replace with the desired Docker image tag

service:
  name: myapachepod-service
  type: LoadBalancer
  port: 80
  targetPort: 80

limitRange:
  name: myapachepod-limit-range
  cpuDefault: "100m"
  cpuMax: "500m"
  cpuMin: "100m"
