apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
        tier: frontend
    spec:
      containers:
        - name: myapachepod
          image: richeb/apachetest:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.appLabel }}
    tier: frontend
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.limitRange.name }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.limitRange.cpuDefault | default "100m" }}
      defaultRequest:
        cpu: {{ .Values.limitRange.cpuDefault | default "100m" }}
      max:
        cpu: {{ .Values.limitRange.cpuMax | default "500m" }}
      min:
        cpu: {{ .Values.limitRange.cpuMin | default "100m" }}
